### ISSUE TITLE
Reduce network requests

### ISSUE THREAD

**Issue by iansvo** [tomusborne/generateblocks#1616]
This issue is an epic to track ways we can reduce network requests. 

- [x] https://github.com/tomusborne/generateblocks/pull/1619
- [x] https://github.com/EDGE22-Studios/components/pull/18
- [x] https://github.com/tomusborne/generateblocks-pro/pull/805

**Comment by tomusborne** [comment]
Related: https://github.com/tomusborne/generateblocks/issues/1613

**Comment by tomusborne** [comment]
Finding a way to reduce the requests for dynamic tag should be a priority. We can see a real-life example of the number of requests being a problem in the issue linked above.

I wonder if a simple local cache when editing the page would help.

**Comment by iansvo** [comment]
I'm working on a POC for that right now. I'll report back when I have something to share.

**Comment by iansvo** [comment]
@tomusborne So far I have a number of PRs that will positively impact this that affect Dynamic Tags, SelectPost, SelectUser, and Global Styles. 

The overall idea for each is the same: we implement tanstack query and leverage the caching mechanisms therein so we don't have to figure out if we need to make the request again or not. We have a QueryClientProvider that wraps key areas and passes the queryClient as a prop to those components so they can use the client. This allows the components to effectively remain just as portable, but now they can share the same caching logic. 

For instance, the Global Styles are the same when we request them, no matter which block it's for. So if we can cache that request, we don't have to ask for the global styles every single time we click on a new block. But if we create a new one, it will invalidate the query and we'll get a fresh result. Otherwise if a minute passes the request will be made again (staleTime). 

Let me know what you think on these PRs.
